import { useState } from "react"
import Head from "next/head"
import Image from "next/image"

export default function Home({ initialAdvice }) {
  const [advice, setAdvice] = useState(initialAdvice)
  const fetchData = async () => {
    const req = await fetch("https://api.adviceslip.com/advice")
    const newData = await req.json()

    return setAdvice(newData)
  }

  const handleClick = (event) => {
    event.preventDefault()
    fetchData()
  }

  return (
    <div>
      <Head>
        <title>NextJS and Tailwind Template</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Advice #{advice.slip.id}</h1>
        <p>"{advice.slip.advice}"</p>
        <button onClick={handleClick} className="p-5 rounded-full bg-slate-400">
          Generate Random
        </button>
      </main>
    </div>
  )
}

export const getStaticProps = async () => {
  const res = await fetch("https://api.adviceslip.com/advice")
  const data = await res.json()

  return {
    props: { initialAdvice: data },
  }
}
